### ISSUE TITLE
View PR review status

### ISSUE THREAD

**Issue by jazzdragon** [uptech/git-ps-rs#123]
I was thinking it would be awesome if we could somehow integrate the PR review status into the `gps ls` command. I know the github integration is out of scope for this project, but I thought I'd kick off a discussion here to determine feasibility and possible approach.

### motivation
 I want to be able to avoid opening github as much as possible, and stay within my terminal. If I have to go into github to see the status of the review process on my PRs, I might as well click the merge button on approved PRs rather than going back into my terminal and using `gps integrate`

### possible approach
We already have some kind of github integration using hooks, maybe we can do something similar here? maybe we can have a `post-list` hook that allows you to programmatically add information / columns to the generated list? in that case, we can use the github cli to pull down the review status for each commit and tack that on to the output.

**Comment by drewdeponte** [comment]
yeah I think doing it with a hook is definitely possible.

I think we just need to make sure it fits our design principles, https://book.git-ps.sh/tool/design-principles.html

The one that is probably the most guiding in this situation is making sure it works with all workflows, including not pull request ones. For example the patch to mailing list workflow.

I think as long as we can come up with a solution that doesn't break the patch to mailing list workflow we should be fine.

**Comment by drewdeponte** [comment]
One thing that I don't know how you are going to get away from going to the pull request in browser for is reading the feedback on the pull request.

So I think you are still end up being in the browser looking at your PR, reading the feedback, seeing that you are approved eventually.

Then coming back to the terminal running `gps ls` to see your patches and see your PR status next to the patches.

Then integrate your patch with `gps I`.

**Comment by drewdeponte** [comment]
Yeah, it seems like it would just be a hook that would get executed for each patch that is going to be listed in the output, and then capturing the stdout from the hook execution and plugging that into the `gps ls` output somewhere.

**Comment by ctsstc** [comment]
I was hoping to display ticket information by hooking into the `gps ls` with something like:

```shell
git log -1 --pretty=%B SHA_HERE | grep -o "FI-[0-9]*" | paste -sd " " -
```

For a given sha it would find all matches for "FI-###" and then join them with a space ie: `FI-10 FI-123`

Utilizing something like iterm's triggers one could then setup a trigger to allow opening the ticket in their browser ie: Trigger that matches on `FI\-\d+` with the action of: `Make Hyperlink` with params: `https://subdomain.atlassian.net/browse/\0`.

**Comment by jazzdragon** [comment]
You can definitely do that with this hook. You might get truncated, but you can increase the space in settings. Give it a try.

**Comment by ctsstc** [comment]
Has this been released on the current `6.4.0`? 

I tried adding a `.git-ps/hooks/list_additional_information` file to my project root with executable rights added, but it didn't seem to change the output of my `gps ls` command. I even tried throwing an `echo "Hello"` in there just to see if it did something. Maybe I'm not implementing this properly, or I'm misunderstanding it's use.

**Comment by jazzdragon** [comment]
Did you turn the hook on in your configuration?

**Comment by ctsstc** [comment]
I did not know there was a configuration that had to be turned on first. I thought it defaultly utilized provided hooks, unless this one is a beta/feature flag for now?

**Comment by jazzdragon** [comment]
It's not a feature flag, but figured not all of the users of this package want to have that extra output. It's all in the docs.

**Comment by drewdeponte** [comment]
See, https://book.git-ps.sh/tool/configuration.html

**Comment by ctsstc** [comment]
Its working 🎉 thanks!

<img width="291" alt="image" src="https://user-images.githubusercontent.com/416814/216442092-d26579af-336b-4067-9a9e-804b011f65d6.png">

**Comment by drewdeponte** [comment]
This was integrated and has been available for a long time. So I am closing this issue.
