### ISSUE TITLE
add + indicator to the `gps ls` command for `int+` scenario

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#124]
If someone for some reason modifies an already integrated patch. We should let them know that they have made local changes to it.

**Comment by jazzdragon** [comment]
@drewdeponte what would be their options at that point? should we let them create a new patch out of their new changes?

**Comment by drewdeponte** [comment]
Yeah if it has been integrated and then they pull it will conflict or leave them with a new commit.

The tricky part is dealing with the ps-id as it should be a new one. But it will still have the old one. So given how edge Casey this is maybe it is just documented to nuke the ps-id in the commit message in this scenario.

**Comment by drewdeponte** [comment]
State representation and the fundamentals of it have changed significantly and this issues no longer makes sense. Therefore, I am closing it.
