### ISSUE TITLE
add a no isolation verification options to the `gps rr` command

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#125]
There are scenarios where people make textual changes, etc. and are lazy and don't want to wait for their isolation verification checks to occur. So we should provide an option for them to override the current configured setting via the command line.

**Comment by jazzdragon** [comment]
@drewdeponte  so something like `gps isolate 0 --no-verify`?

**Comment by drewdeponte** [comment]
Yeah that is what I am thinking. Maybe we do that on rr, iso, and int?

Part of me doesn't like it because it allows people to not follow the smart process.

But at the same time I am sure there will be edge cases where you might not want it to run.

🤷‍♂️

**Comment by Alizter** [comment]
One way to discourage users from using it is to make the option long. Something like
```
--no-isolation-verification
```
will typically dissuade people. Is it a good idea? That is another question.

**Comment by drewdeponte** [comment]
That is a good point. I like the idea of using the full long name `--no-isolation-verification`

**Comment by drewdeponte** [comment]
This has been integrated into mainline with the option `--no-isolation-verification-hook`. Therefore, I am closing this issue.
