### ISSUE TITLE
Add patch series support

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#13]
Add the ability to request review a series of patches and the other appropriate commands. This may need to be supported across a number of commands. For example since it would like be built into **branch**, and **branch** is the under pinnings of **sync**, **request-review**, and **integrate** it would likely need to be supported in all of those commands.

Related issues.

- [ ] #142

**Comment by drewdeponte** [comment]
I know we had this feature in the previous incarnation of git-ps. The reason this feature was really created was because of a limitation in GitHub though.

The problem it is helping people address as a work around is that when you have a branch in GitHub that has comments on lines of code. Anytime those lines of code are modified (even when they don't address the comment) GitHub hides the comments assuming that you have addressed the issue.

Since the comments on the lines of code were gone the reviewers had no easy way to identify the comments where addressed or not once the new version of the patch was pushed up. You might be saying well if you are doing the Git Patch Stack methodology you don't really have a difficult time because PRs are small enough it is easy to just look and see. This is true. However, other people are in the process of learning and adapting to the Git Patch Stack workflow and therefore are still creating very large patches. The large patches combined with GitHub's hiding of comments for lines that have changed. Caused people to look for another solution.

That solution was to make additional patches specific to each of the requested changes and request review of the series of patches. That way reviewers could then go look at each of the commits in the PR and review them individually seeing that they addressed all the comments.

The other theoretical use case that this helps with is when you are working on a team that requires you do Feature Branches because then you could simply request review of the series of patches that compose up your feature.

Anyways, so I am some what hesitant to include this feature in this new version git-ps. I would love to hear anyones thoughts or opinions on this to help push me one way or the other on this topic.

**Comment by jazzdragon** [comment]
I agree that if you have small enough patches, you won't need this feature. However, I think it should still be implemented if it lowers the barrier for entry for developers, as adopting this method of work can be incremental.

Another use case is for teams across different timezones, working asynchronously. Say I have 5 patches in my stack which build on top of each other, and I submit the first one for review. If the review cycle takes a day for each patch (if we're on the other side of the globe, or the review happens once a day for a person), this can lead to a painfully slow process and long living branches. Instead, the team can have an understanding that the PR is actually a series of patches, and should be reviewed that way. If the reviewer has a comment on patch #3, I can still merge in the first two, address the comment, and submit for another review.

**Comment by rgrinberg** [comment]
> The other idea was to actually formalize the concept of a patch series in the tool and visually expose it and track state of that concept inside of the gps ls command, etc

IMO, that would be the right way to go. In mailing lists, the unit of work that is submitted to upstream is a series of patches and not a single patch. Patches are more of a unit of code review. Something that helps reviewers understand a larger change step by step.

>  Part of the complexity is also around the pulling of changes down from a branch as well which we are also exploring further

This is when other contributors push to your PR's branch on github, right? The way I dealt with this is pulling the patch series branch manually, and then cherry picking the new commits into my master branch. Kind of manual, but it seemed to work fine.

Could you explain the state tracking issue a bit more?

**Comment by drewdeponte** [comment]
I am reopening this issue as a feature request so that we can continue discussion around it actively.

**Comment by rgrinberg** [comment]
Thanks for the detailed response. I guess something that feels natural to me is:

* Attach all the current patch state to patch series
* Allow a patch to only belong to a single patch series at a time

Which is quite similar to this suggestion:

> You can say maybe we have another Patch state which indicates it is part of a Patch Series and to include the associated Patch Series identifier. But then we are saying it's previous state is now gone. So how do we handle the case where it was previously requested review / synced and what does that even mean?

The patch series to which it belonged would be expanded to include the additional patch. I'm not seeing the problem here I suppose.

**Comment by drewdeponte** [comment]
I have been doing some more thinking on this. I think I have come to the conclusion patch series should definitely be a formal thing. There are still bunch of questions around this in my head. But, I am feeling pretty good about the idea of having the following operations.

* creating a patch series given a series of patches (start-patch-index & end-patch-index)
* expand a patch series up one in the stack
* expand a patch series down one in the stack
* support displaying patch series in `gps ls` output


I think to truely understand the states we need to bulid a table out to understand what happens in all the different states.

  BranchCreated(String, String), // branch_name, patch_stack_diff_hash
  PushedToRemote(String, String, String, String), // remote, branch_name, patch_stack_diff_hash, remote_diff_hash
  RequestedReview(String, String, String, String), // remote, branch_name, patch_stack_diff_hash, remote_diff_hash
  Integrated(String, String, String) // remote, branch_name, patch_stack_diff_hash

* create a patch series from a single patch
* create a patch series from a series of patches
* add an existing patch to a patch series

The following is a table describing the various initial states of a single patch and what would happen if we 

| fist header | second header |
|---|---|
|foo|bar|

**Comment by rgrinberg** [comment]
> In pratice this could look something like the following.

For visual clarity, you might want to consider hierarchical output. Something like `pstree` is what I'd imagine.

> Do we have a rules or something where we say that we follow the rules outlined above if in "Creating a Patch Series from a Solo Patch" if only one patch in the Series has state?

In this case, the user is doing something that is contradictory/does not make sense. In which case, I would suggest not worrying not too much about this and let the user describe what the final state rather than guessing intent. In practice, this would mean the following for my use cases:

* Mapping PR's to patch series
* Mapping Patches to patch series.

So if there was a command that allowed me to edit these mappings directly (similar to an interactive rebase?), that would be more than enough for me.

**Comment by drewdeponte** [comment]
The conflict I am having is that I agree from a UX standpoint the user should be able to describe the end state they want and not have to worry about the steps to get there.

But, if we let the user do that there are scenarios that aren't even edge cases where we would have to assume what their intent is. These are scenarios around what to do if a patch is included in a patch series after it has already been synced or requested review, etc. Or scenarios where multiple patches have been requested review, synced, etc. prior to being put into a series of patches.

I think from a user experience standpoint it is too much to expect the end user to understand the complexities of these scenarios, all the supposed rules around them, etc.

To simplify the UX and make it more consistent for the user I am now thinking that we check for these cases upfront and bail out with explicit very meaningful error messages explaining to the user why we weren't able to create the patch series. But we also need to provide functionality to let them explicitly address each of these scenarios.

For example if the user tries to create a patch series with a patch that has already been requested review. It should abort notifying the user they can't create a patch series with a patch that has already been requested review. To address this please `close-review` of the specific patch.

I think we would also need to add checks to all of the other patch specific operations to see if the user is attempting to perform an operation on a patch when it is already part of a patch series and abort with meaningful error message and provide guidance on how to address the issue. Most likely by moving the patch out of the patch series and then performing the individual patch operation.

As much I don't really like this complexity from a UX standpoint and from an architectural spread standpoint it may just be the reality of the situation.

**Comment by ctsstc** [comment]
Thanks for opening this back up and taking a deep dive into it. This is still one of the features I miss most about the last major version of `git ps` I think this was most useful to show proof of change during peer review. 

I also volunteer on a project where I would like to use git-ps as my tooling and strategy, but the team I help wants large monolithic pull requests at the end of the day -- I know there's an escape hatch via the branching commands, but it feels like it's an orphaned process outside of the normal flow of git-ps right now.

**Comment by drewdeponte** [comment]
Yeah, this I believe is a critical piece for open source projects and supporting the open source workflow better.

**Comment by drewdeponte** [comment]
Ok, so I have been contemplating this some more.

Where I think I am netting is that I think `gps` should take the stance of keeping the status for patches distinctly separate from the status of a series of patches.

Maybe for the `ls` command we would have an output like the following for the patches where we could see how the patches relate to a patch series or multiple patches series.

```
[index] [status] [patch-series-identifier]   [sha] [summary]
```

I am thinking also as part of `ls` output we would also list the patch serieses maybe with a format like the following.

```
[patch-series-identifier] [status]  [patch-series-name-aka-branch-name]
```

Taking this stance would mean that we could side step all the complicated scenarios of trying to convert a patch in whatever state it is in, into a patch series. Instead just shows the current state to the user and allows the user to do what they want with it as an individual patch. At the same time we also show them the patch serieses and their statuses. So if the user wants to have a patch and request review for an individual patch and then also include it as part of a patch series or even multiple patch series who are we to tell them no.

I also think this might be more reasonably doable as long as before a patch becomes part of a series it gets a patch-id attached to it. Because then processing patches we could figure which patch serieses it is tied to and present it.

I think it also makes sense to start with an interface as simple as a patch index range with the name. If you run the command again and include a different patch index range (either smaller or larger) it doesn't matter it just replaces the patch series with the new collection of patches and updates the state of thhe patch series.

**Comment by ctsstc** [comment]
I think you would need to have a collection of the SHAs within an index in case any rebasing re-orders them or someone goes in and changes one of the commits in the range. It would then have that series considered "dirty" or maybe even invalid; you would have to recreate the branch given the new state which could be completely different.

**Comment by drewdeponte** [comment]
Yes we would have to track state for the patch series in the same way we track state for individual patches. The difference would be the computation for identifying the change would be done differently but we would be storing the same state.

**Comment by drewdeponte** [comment]
Ok, so this weekend I did some heavy thinking about it and I think I have had an important realization.

My issue with the feature has largely been trying to figure out state tracking and complications around that. Not to mention the need to update the state tracking format. The other complexity that comes into mind with the state tracking and the format is the need to be able to sync state tracking information across remotes so that you can sync stacks across remotes and have the appropriate state information irrespective of which machine you are on. Beyond that we currently have a bug , #175 related state not being tracked specific to stack.

Anyways, while thinking about all of this I explored the idea of throwing out state tracking all together, or at least the majority of it and wondering if I could simply compute the state based on the natural state of the Git repository. The thing I like about this is that we aren't trying to fabricate/represent a state that somewhat parallels what Git already knows about. We are just computing the states based on what Git knows.

If we think about the various states that a patch can have it is as follows.

```
  WithoutBranch,
  BranchCreated,
  BranchCreatedButLocalHasChanged,
  PushedToRemote,
  PushedToRemoteButLocalHasChanged,
  PushedToRemoteButRemoteHasChanged,
  PushedToRemoteButBothHaveChanged,
  PushedToRemoteNowBehind,
  PushedToRemoteNowBehindButLocalHasChanged,
  RequestedReview,
  RequestedReviewButLocalHasChanged,
  RequestedReviewButRemoteHasChanged,
  RequestedReviewButBothHaveChanged,
  RequestedReviewNowBehind,
  RequestedReviewNowBehindButLocalHasChanged,
  Integrated
```

Looking at the possible states I think the only thing we can't know from the state of Git itself is the concept of having `RequestedReview`, interestingly it's sub-states are things that I believe we can compute.

So even if we imagine that we eliminated the `RequestedReview` state for simplicity, which I don't think we would do, but just to simplify the problem space for now.

Then we can ask ourselves if computing the state this way would resolve the related bug, #175 . I think the answer is yes it would.

Then we can ask ourselves what does this mean for the concept of a patch series. Well if we assume that a patch series is represented in Git as a branch we should be able to tell all the same state information about a branch with multiple patches as we do with a branch with a single patch.

I think the other realization around this is that I was struggling to figure out how best to deal with the possibility that patch could live in multiple branches because the current interface doesn't support that. But I think if we just take the assumption that a patch can live in multiple branches because Git naturally supports that and we compute state based on that, then we just have to adjust the `gps ls` command to represent that state in someway. Maybe we still keep `gps ls` focused on the current state with the state as it is now, but maybe we include an additional indicator to show that a patch is part of another stack or something. And then there can be a different command to maybe see all the stacks or maybe even all the branches that a patch is in?

This is where I have less specifics in terms of exactly how I want to do that.

But I am feeling like the core of all of this is to switch over to computing state about patches and eliminate as much of the state tracking as possible.

I would love to hear anyones thoughts on this?

**Comment by drewdeponte** [comment]
Ok, I have been implementing patch series support into all of the commands and I got to `integrate` and have been thinking over the last day or so about the ideal interface for it in terms of patch series support.

Let me describe the other commands and the thought process around them. So, `request-review-branch`, `sync`, `request-review`, `isolate` all take an argument that is `<index-or-range>`. That is it takes either an explicit patch index, e.g. `5` or a range of patch indexes, e.g. `2-5`. These generally make sense in my mind as these commands are all revisionary as they are about evolving either a patch or a patch series to a point at which you ready to integrate either the patch or patch series. This is why it feels fine to me to simply provide the patch index range to identify the latest state of the patch series.

The `integrate` command however, is *not* revisionary in my mind. Or is it? I guess it really depends on what you want. Maybe there should be a command line option to control if it is revisionary or not. Maybe `-f` is that indicator. In the case where it is revisionary (maybe with `-f` option) a patch series could be specified via a `<index-or-range>` the same as the other commands. However, in the non-revisionary mode it feels like you should have to specify the patch series in a non-revisionary way, maybe via the branch name.

Anyways, I am definitely open to thoughts on this one as I want to end up with a really nice logical interface.

**Comment by jazzdragon** [comment]
What would integrating a range look like? will it integrate one patch at a time, or squash them together?

I don't know about overloading the `-f` flag here, seems like if we want to allow this specific behaviour we should add a flag or config for it.

Great work!

**Comment by drewdeponte** [comment]
Integrating a patch series would simply be a push of all the patches in that series up. Just like integrating a single patch is a push of that single patch up.

If you want to do one at a time for some reason you are looking for something more like `batch-request-review` but `batch-integrate` which doesn't exist.

**Comment by jazzdragon** [comment]
I'm just wondering how the hooks will play into it. Will we isolate all of them together?

**Comment by drewdeponte** [comment]
Yes, currently with the existing `branch` command the isolation is of the entire patch series, not of the individual patches in the series. I think this makes the most sense for the majority of use cases so I will probably keep it that way initially with addition of patch series support in general.

Other people have brought up wanting individual patch isolation in the past. So we will have to keep discussing that and the potential benefits and drawbacks and see if we get to something that makes sense.
