### ISSUE TITLE
make `gps ls` work when in middle of rebase

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#137]
The ideal would be that when we are in the middle of a rebase of the patch stack we can still run `gps ls` and see the current state of which patches have been played already, where we are stopped at, and which patches are to be played still.

Not sure exactly what this would look like visually.

Maybe just the patch stack with some `------` line indicating where it is stopped at with the patches to be played above it or something.

**Comment by Alizter** [comment]
Do you think its possible to have `gps rr/branch` also work in the middle of a rebase? It might be handy if you want to publish some patches without resolving all the conflicts in your stack.

**Comment by Alizter** [comment]
As discussed on slack, something like
```
0           5f375f2 nix: add flake
1           af208c9 chore: add macos and windows runners
2           6a9eb75 exploration: replace gpgme with rpgp
<><><>< Rebase in progress ><><><><
3           bf0944d add expect tests
```

**Comment by drewdeponte** [comment]
This feature has already been integrated into `main`. Therefore I am closing this issue.
