### ISSUE TITLE
Perform isolation checks before hook

### ISSUE THREAD

**Issue by jazzdragon** [uptech/git-ps-rs#139]
When trying to integrate a patch, it sometimes fails due to some reason (for example, my patch is behind or the patch differs). This happens after the isolation hook runs, and is quite frustrating because then I need to wait for the hook to run again.

Can we move those checks to run before the isolation hook?

**Comment by drewdeponte** [comment]
I am not sure what checks exactly you are referring to.

When the `-f` option is provided it doesn't do any additional checks.

When there `-f` option is NOT provided it does the following checks after the isolation verification currently.

- verify that the commit has a patch stack id
- verify that the patch has an associated branch and has been synced
- verify remote request-review branch has exactly one commit
- verify that the remote rr branche's patche's diff hash matches that of the local patch in the patch stack
- verify that upstream base hasn't left the remote patch behind

I guess it could make sense to let all those verifications happen prior to the isolation verification.

**Comment by drewdeponte** [comment]
Closing this as it has been integrated into mainline.
