### ISSUE TITLE
Fail GPS isolation earlier when uncommitted changes exist

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps-rs#145]
It's a sad day you've waited to get past all your tests and you find out there was a lingering file that didn't make the cut and isolation fails due to uncommitted changes existing. Or maybe you got excited and started working while the tests were running and created uncommitted changes (I guess this could happen after an initial check anyways).

It would be nice to have isolation fail early before running builds and tests. I still think there has to be a final check anyways too; which can help catch instances where you may have missed committing some type of build artifact potentially.

**Comment by drewdeponte** [comment]
Isolation should be exiting early based on these things before running. Are you sure you are running the latest version?

This was addressed with https://github.com/uptech/git-ps-rs/issues/139

**Comment by ctsstc** [comment]
I will double check; I may have just started making changes mid-isolation potentially too.

**Comment by ctsstc** [comment]
Verified this was likely a me issue 👍
