### ISSUE TITLE
Increase short SHA length to 7 characters from 6

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps-rs#159]
When displaying short SHAs when running `gps ls` or `gps pull` if there's a longer SHA it allows for extensions like GitLens in VSCod to recognize the SHAs when they show up in the terminal and provides useful tooling around the SHA.

With 6 characters I get "No matching results"
<img width="248" alt="image" src="https://user-images.githubusercontent.com/416814/188990758-600c5338-65ef-4d8f-9b62-1eb480f2b865.png">

With 8 characters I get this useful toolset that helps me dig into the changes while staying in VSCode
<img width="739" alt="image" src="https://user-images.githubusercontent.com/416814/188990833-5ab70abc-e71e-44a2-badb-5ae35a70bbea.png">

EDIT: It seems 7 characters are enough for the extension to recognize the SHA.

**Comment by drewdeponte** [comment]
I am closing this issue as it has been integrated into `main`.

**Comment by ctsstc** [comment]
Thanks 🎉 looking forward to the next update
