### ISSUE TITLE
Add reminder to create WIP commit when uncommited changes are found

### ISSUE THREAD

**Issue by Alizter** [uptech/git-ps-rs#160]
As discussed on slack, it might be nice to have `gps` autostash the dirty git tree when doing `git rr`. On the other hand, people should really be making WIP commits, so perhaps `gps` could just suggest doing that instead.

**Comment by drewdeponte** [comment]
I think adding auto stashing is a little too much automation. People should have to conciously decided what they want to do. Maybe as you say having a reminder to create WIP commits when this happens, to help people get into the habbit.

**Comment by ctsstc** [comment]
I would love an "auto-stash feature" that displayed a warning to let you know that it stashed changes.

I guess ultimately you want it to be slotted into your stack, so maybe an auto-commit WIP feature with a warning could be nice as well. I would then likely want a feature that would prevent me from trying to integrate WIP patches unless overridden with a force flag of some sorts.

**Comment by Alizter** [comment]
Something else I thought about today. Sometimes it is important to have the distinction between staged and unstaged changes. Perhaps it would be possible to do a double WIP progress commit for each kind of change.

You would start by committing the staged, then staging the unstaged and committing. To undo you reset the unstaged WIP commit, unstage them and then undo the staged WIP.

That way we would preserve the changes exactly.

**Comment by drewdeponte** [comment]
I generally don't stash my current work in progress. Instead I create a WIP commit that becomes part of my patch stack.

**Comment by Alizter** [comment]
I think what is actionable in this issue is the following:

When gps encounters a dirty tree and refuses to rebase it should print an error message saying the following:
```
gps requires a clean working directory but it looks like yours is dirty.
Hint: try creating a WIP commit.
```
or a variant thereof.

**Comment by drewdeponte** [comment]
Yeah, that is what I am thinking is something along those lines.

**Comment by drewdeponte** [comment]
This has been integrated into `main`. Therefore, I am closing this issue.
