### ISSUE TITLE
Add a "batch request review" mode for doing multiple rr's

### ISSUE THREAD

**Issue by Alizter** [uptech/git-ps-rs#173]
A common use case is to `gps pull` a patch stack and needing to rr multiple patches afterwards. Currently the best you can do is
```
gps rr 0; gps rr 1; gps rr 2; ...
```

It would be nice if we could have a "batch request review" feature so that we could do

```
gps brr 0 1 2 3 4 5 6
```

for the same thing.

**Comment by drewdeponte** [comment]
This has been integrated. Therefore, I am closing this issue.
