### ISSUE TITLE
Document cherry-picking collaborator commits workflow

### ISSUE THREAD

**Issue by Alizter** [uptech/git-ps-rs#177]
We should document the workflow where you have rr'd a patch and then a collaborator pushes their own commits in your PR and you want to squash them into your local patch stack. The correct thing to do would be cherry-pick the commits from the PR and then rebase and squash.

**Comment by drewdeponte** [comment]
I wrote this up here, https://book.git-ps.sh/guides/absorb-changes Therefore, I am closing this issue.
