### ISSUE TITLE
Proposal: Ability to rr commits that depend on other commits.

### ISSUE THREAD

**Issue by Alizter** [uptech/git-ps-rs#189]
I think that https://github.com/uptech/git-ps-rs/issues/13, if it ever gets implemented, will be a killer feature. I have a similar use case which I will describe here that shares many of the features, but is not exactly the same.

I want to have the ability to request-review on patches that rely on other patches.

## Use case

Say you are implementing a large feature and you have the following commits:
```
commitA (refactoring a lot of code)
commitB (exposing some new API)
commitC (actually using the new API in the implementation of your new feature)
```
Usually, one would submit a PR with all 3 commits, but this can be very difficult to review. First of all there is no guarantee that the  commits work on their own or do what they say. This means that a reviewer will have to spend a lot of time sifting through all the details all at once.

When using `gps`, you might think that it will make this workflow easier. You can have that stack of patches locally and `rr` each of them separately. But from the point of view of the reviewer, `commitA` looks completely useless on its own without seeing what `commitB` and `commitC` does.

If after some time, you do manage to get `commitA` merged upstream, you run into the same issue with `commitB`. Now the reviewers will ask, "Why expose this API?". For that your motivation would require them to understand what you are trying to do in `commitC`.

You might argue that `commitB` and `commitC` need to be squashed together, but that will make reviewing the new API harder. In many cases, the API should be something that stands on its own to make it easier to review and have attention paid to it.

## Feature Proposal

What I would propose is to have a way to `rr` commits that are dependent on other commits. In the above story, I can `rr` on `commitA` no problem, but when I `rr` on `commitB` it will be an error. I would suggest that in this case, `gps` submits both `commitA` and `commitB` in the isolated branch and submits it kind of like a patch series. Similarly for `commitC`, it would include both `commitA` and `commitB` before.

This way, you would have 3 PRs open, showing the story of your feature gradually. When a commit gets merged, the `rr` would omit the dependent commits since they are already merged.

Let me know what you think.

**Comment by drewdeponte** [comment]
Yeah, I definitely see this use case. Especially in the OSS world. There are a couple things that you should be doing that aid in the workflow you described.

**Comment by ctsstc** [comment]
One interesting thought that really only applies to github is that when you open a pull request you can select what it's based upon, thus it will only show those related changes. Ideally that would work with this workflow where a commit is not based upon `main` but instead of the patch or patches below it. Of course of it to be based on the patches below it there would need to be a branch that exists that is composed of the series of patches below it.

This gets back to the series/range logic though that if a commit changes down the stack all related open branches need to then be updated with those changes which would be great to have automated.

**Comment by drewdeponte** [comment]
The problem with doing the PRs with a base other than `origin/main` is that it acts as the destination of where it would be green button merged. So if you set the base to the branch below it in the stack, etc. Then the merging doesn't play out correctly.

**Comment by drewdeponte** [comment]
I think the only reasonable thing to do given GitHub & Bitbuckets behavior is to have the patch series be created as separate commits within a single branch for the series. This is currently supported by the `branch` sub-command so I am closing this issue.
