### ISSUE TITLE
If GPS fails it should return a non-zero exit code

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps-rs#192]
Rather than just logging a message it should return a non-zero exit code.

I would like to get the exit code from gps to determine with my tooling if I should continue to try integrating or not, if there was an error. Currently gps always returns a 0 exit code it seems, at least when I'm trying to run an integration.

Current error message with 0 exit code:

```
Error: IsolationVerificationFailed(IsolateFailed(HookExecutionFailed(ExitStatus(70))))
```

**Comment by drewdeponte** [comment]
This has been integrated so I am closing this issue.
