### ISSUE TITLE
Add option to the `gps branch` command to have it create the remote branch

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#196]
We need to add an option to the `gps branch` command, maybe the `-r` option to tell it to also create the remote branch as well.

**Comment by Alizter** [comment]
I have a patch for this. Howeer https://github.com/uptech/git-ps-rs/pull/200 needs to merge first before I can push it.

**Comment by drewdeponte** [comment]
This has been integrated and therefore I am closing this issue.
