### ISSUE TITLE
Add env var for overriding config

### ISSUE THREAD

**Issue by Alizter** [uptech/git-ps-rs#210]
An idea perhaps for the future if we ever end up having more config values is to have an environment variable that allows us to override the current config. Something like:
```
GPS_CONFIG="branch.asdf = false"
```
That way it is easy to disable things like hook verification etc. on the fly.

**Comment by drewdeponte** [comment]
I think hooks should be controlled via command line switches in the specific commands rather than adding another config layer. Therefore I am closing this issue.
