### ISSUE TITLE
Don't skip int verification when using -f flag

### ISSUE THREAD

**Issue by jazzdragon** [uptech/git-ps-rs#217]
When integrating with `-f` the verification process that shows the user the changes before they confirm is skipped. Seems like it should still happen, no?

**Comment by drewdeponte** [comment]
That is a good question. Currently when you use the `-f` or `--force` switch with integrate it skips two things.

1. the optionally configured prompt for reassurance

**Comment by jazzdragon** [comment]
When I think of force as an option, I think of the second point, not so much the first. Especially when it's configurable.

**Comment by drewdeponte** [comment]
Yeah, I a agree. It is a bit confusing in the current approach.

We should change it.
