### ISSUE TITLE
Replace home-dir with a cross-platform solution

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#218]
The idea is to do this so that `gps` would be able to be built on Windows platforms as well.

**Comment by drewdeponte** [comment]
Could probably use this. https://crates.io/crates/homedir

**Comment by Alizter** [comment]
This is fixed by #221

**Comment by drewdeponte** [comment]
This has been integrated with commit 39787e8. Therefore, I am closing this issue.
