### ISSUE TITLE
Figure out password manager on non macOS operating systems

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#227]
On macOS systems you have the Apple provided Keychain, which securely stores passwords and allows applications to securely retreive them.

We use this on macOS for instance to make it so that users don't have to enter their SSH key password everytime a signed commit is created, when the user has SSH key based signing configured in Git.

I am not sure if there is a singular standard password manager on Linux distributions or even on Windows. Hence, this issue.

If there isn't a standard on those platforms then this issue will probably have to evolve into figuring out some way to support different ones on those platforms or something. It is probably worth looking at what SSH does on those platforms natively as inspiration.

**Comment by Alizter** [comment]
On Linux we typically use GNOME keyring or KDE keyring. Its typically straightforward to detect which.

Fo Windows, Ive heard that Credential manager is the equivalent. This is apparently what python bindings use as a cross platform equivalent.

**Comment by drewdeponte** [comment]
@Alizter given that I am living on macOS these days this will probably need someone who lives on Linux to implement the Linux side of this.

**Comment by Alizter** [comment]
@drewdeponte I'll take a look when I get the time.

**Comment by drewdeponte** [comment]
This has been integrated into mainline. So I am closing this issue.
