### ISSUE TITLE
Intent to support stack push and pop? (like Mercurial Queues or Stacked Git)

### ISSUE THREAD

**Issue by Kobold** [uptech/git-ps-rs#229]
First, thank you for the project. I love the Github integration! Making patch stack based workflows work with Github code review is a huge pain point and has blocked me from using patch stacks professionally for the past decade.

I'm just curious if you intend to support patch pop and push? I find pop/push makes decomposing changes into appropriate patches as one works conceptually easier. Here's an example of how Stacked Git's patch stack works: https://stacked-git.github.io/guides/usage-example/#working-with-multiple-patches

An example use case is working on a given patch and then determining that it would be better to do a complex refactoring as patch prior to the current patch. A push/pop stack workflow makes it easy to bounce back and forth between the primary patch and the preliminary refactoring patch as I discover what the refactoring fully needs to do. It seems like a `gps rebase` based workflow editing specific patches means you need to know which patch a change belongs to before you start editing. Absorb based workflows seem better at solving this, but it seems they are limited to edits that make sense in the final result of the patch stack. That is, it's not clear how to absorb a change to an intermediate patch if the location of the change is deleted by the end of the patch stack.

Just my personal workflow tastes, of course make the tool that works for you!

**Comment by Kobold** [comment]
Push and pop in this context are moving between patches managed by the patch stack tool. A more dynamic `gps rebase` is a good analogy. Imagine you have a single `edit` marked in a `gps rebase`, but you can move it between commits. Using Stacked Git examples, `stg push` is "move move me to be `edit`ing to the following commit in the patch stack" (push on the following patch). `stg pop` is "move me to be `edit`ing the prior commit in the patch stack" (pop off the current patch). The dynamic and fun part is that you can keep changes to the working copy (where possible without merge conflict) as you do these operations.

So if you have changes that you want to "absorb" with manual selection:

```bash
# Move to an earlier patch keeping the working copy, select changes and add them to the patch.
stg pop -k 
git add -p && stg refresh --index

# Again move earlier and add changes to the patch. Hard to do with `rebase`.
stg pop -k
git add -p && stg refresh --index

# stg has named patches. Add the rest of the changes to a different patch.
stg goto -k patch-far-away-in-the-managed-stack
stg refresh
```

> Where would you be pushing from? Is it that push is really just making a commit from what you currently have staged?

Imagine this as always being `edit`ing during a `gps rebase`. Push changes you to be `edit`ing the following commit in the patch stack.

> Also what would happen to the commit that you pop off the top of the stack. Does it just get dropped?

Again as if you are `edit`ing during a `gps rebase`, pop changes you to be `edit`ing the prior commit in the patch stack.

---

As a nomenclature aside, "push" and "pop" comes from Quilt [1] which is 20+ years old and was originally a Linux kernel dev tool. Mercurial Queues (released in 2006ish?) and the subsequent git patch queue implementations (Stacked Git, TopGit, Guilt) use the same naming. This probably isn't news to ya, but just want to make sure I'm clear.

[1] https://en.wikipedia.org/wiki/Quilt_(software)

**Comment by Kobold** [comment]
Lots of good commentary on this HN thread about Stacked Git: https://news.ycombinator.com/item?id=27305521

**Comment by drewdeponte** [comment]
Ok gotcha. I think I understand. Seems like it would be trying to solve the same things that #138 is to solve just in a deferent way by having something where edit can move up and down with push and pop.

#138 approach allows you to jump directly to that operation on a patch without having to navigate up and down over other patches with push and pop. 

Unless I am missing something?

Please enlighten me if I am missing a piece of the puzzle.

**Comment by drewdeponte** [comment]
So I looked at Quilt some more. And if I understand push and pop correctly from the man page. It sounds like there is the patch series file and then the push and pop controls which patches are applied or not applied to the base from the series file. So it keeps track of the top most one that is applied so it knows what to apply or revert.

In gps currently we don't have something equivalent to the series file. We just have the stack of applied patches.

Maybe there could be an option with gps to have to branches one equiv to the series file and another equiv to the applied patches stack.

**Comment by Kobold** [comment]
Thank you for your time and consideration! Though I don't think #138 is a complete match to the StGit/MQ user experience, it's clearly the easiest step in that direction for gps. I'll close this issue to aid in project housekeeping.

I think your approach to using multiple branches as the series + applied stack is smart — [TopGit does something similar](https://github.com/mackyle/topgit#readme) though its approach of two branches _per patch_ gets out of hand quick.

Thank you again for taking on the problem of interfacing patch stacks with Github/GitLab reviews! None of the other patch stack implementations have tackled this and I can't in good faith move companies I work with to Phabricator or equivalent.
