### ISSUE TITLE
gps iso should give better error messages when it cannot isolate

### ISSUE THREAD

**Issue by Alizter** [uptech/git-ps-rs#230]
When doing `gps iso` on a patch that cannot be isolated from one that comes before, `gps iso` outputs a rather cryptic message:
```
$ gps iso 12

Error: CherryPickFailed
```
Ideally we should have a proper error message here and perhaps some information about the patch that is causing the problems.

**Comment by GRyanParoz** [comment]
I have had this same issue in the past 24 hours, the circumstances were that a local patch existed prior to the isolated patch, creating a merge conflict in the cherry pick. (So this case, at least, is one that should have proper messaging)

**Comment by Alizter** [comment]
A thought: It might be possible to query git blame on the files that the patch modifies in order to come up with a problematic candidate.

So if commit B modifies file `foo` and commit A has also done that, then assuming B comes after A in the stack and you do `gps iso 2` to isolate B, then you can do git blame on `foo` and find `A`.

**Comment by drewdeponte** [comment]
Yeah, we should look at what we can do simply from modifying the error to include contextual data and improving the error message as part of this task.

Then if we want to fetch more contextual data we can break that out into a separate issue for discussion, etc.

**Comment by drewdeponte** [comment]
At least the initial version of this has been integrated into mainline. Therefore I am closing this issue. If we want to change it in the future we can make a more specific issue for it.
