### ISSUE TITLE
Figure out how we want to show patch series when branch is a generated one

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#243]
Currently when you run the `gps ls` command with a patch stack containing a series of patches that are all grouped together by branch name that was generated and there is only that one branch associated to the patches. It simply shows the status information as follows.

```
main tracking origin/main [ahead 3]
2    d1f815d Change Car to Zar                                  ( l )
1    a0e33dd Change Bar to Car                                  ( l )
0    decd28d Change Foo to Bar                                  ( l )
```

This behavior is to hide the noise of branch names when dealing with single patches where you generally don't care about branches unless they are explicitly named, or there happen to be multiple branches associated to the patch.

But in this case we do need to know that they are part a patch series somehow.

**Comment by drewdeponte** [comment]
I was just thinking about this some more. One potential option would be to make it so that when creating a patch series the first time you have to provide the branch name. Then it wouldn't be a generated branch name and it would show up.

**Comment by drewdeponte** [comment]
Yeah, I have thought about this a bit more and I think that requiring a name when creating a patch series makes a lot of sense and is probably the right way to go.

**Comment by ctsstc** [comment]
I agree on an explicit name, because no single commit is going to encapsulate a patch series' name properly, since they are working together to accomplish a feature [name] more-than-likely. Otherwise it would feel abrupt like how Github pulls the first commit's message as the PR's default comment, which never fully describes the multiple commits and what they're working to accomplish together.

**Comment by Alizter** [comment]
How is it you create a patch series again? Will that be the time when the name is requested?

**Comment by drewdeponte** [comment]
Basically the idea is that a patch series is created when you provide a patch-index-range and none of those patches have an associated branch.

An example of this might look as follows, `gps request-review-branch -n feature_x 2-5`

**Comment by Alizter** [comment]
Right and I suppose if `-n` is not supplied we either error and require it or prompt the user?

**Comment by drewdeponte** [comment]
Yeah, right now we error. I generally don't like prompting in cli because it generally breaks the ability to easily script with the cli.
