### ISSUE TITLE
Make `ps-id: <UUID>` an excluded header in a commit

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#25]
Right now the `ps-id: <UUID>` is appended onto the end of the message similar to sign-off. However, people care about seeing sign-off and they don't really care about seeing the `ps-id: <UUID>` is the thought. So maybe it should be moved to an excluded header in the commit similar to a gpg signature. I think the details around this can be seen in git's `commit.c` file.

The other thought around this though is that users might need to/want to understand the `ps-id: <UUID>` because in the scenario that they squash two patches together that both have `ps-id: <UUID>` they are going to have to pick one.

So, maybe it shouldn't be hidden. I don't know at the moment. Open to other thoughts though.

**Comment by drewdeponte** [comment]
This has been integrated. Therefore I am closing this issue.

**Comment by Alizter** [comment]
@drewdeponte I think we can reopen this as there is still the question of moving the ps-id into the excluded headers.

**Comment by drewdeponte** [comment]
@Alizter we need to figure out a number of things related to that though which makes me feel wi should open up a research ticket to investigate it.

1. We have to figure out if it is even possible to include it as an excluded header like the gpg signature. I don't know if this is a generic concept that Git even supports. I just know that GPG signatures are encoded in there so figured it **might** be a generic concept supported by Git.
2. We need to figure out how we are going to manage the user picking a ps-id to keep when squashing two patches together.
