### ISSUE TITLE
Add visualization of patch series on the left

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#252]
When you have a decent number of patches in a series in a stack that has other patches/patch series. It gets to be difficult to visually track the top most and bottom most patch in a patch series from the right side to the left side.

So this issue is to figure out some way to visualize the patch series on the left so that it makes it easier to visually track from the top and bottom most patch in a patch series to the indexes on the left.

**Comment by drewdeponte** [comment]
Given that the goal of this was to help visual tracking from right side to left side. I addressed it by adding the alternating in background color for patch series. Therefore, I am going to close this issue.

**Comment by Alizter** [comment]
I've seen the tweaks and I think they are a pleasant improvement.
![image](https://github.com/uptech/git-ps-rs/assets/8614547/8ee967dd-b555-45f5-9394-e2eb34433572)
