### ISSUE TITLE
Document Patch Stack ID

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#271]
There always seems to be confusion around the Patch Stack ID that is added to the commit messages.

So we should document the following.

* what it is
* how we use it
* picking a ps-id when squashing
* what happens to ps-id when fixing up
* can we hide it
    * kind of with the HTML comment tagging
    * is hidding it really a good thing since the developer needs to be aware of it for dealing with squashing

There may even be more things worth talking about related to it. But we should create at least a doc to cover the above items.

**Comment by drewdeponte** [comment]
What is it?

The Patch Stack ID or ps-id is simply a Globally Unique Identifier (GUID) that is added to the commit message of a commit when a commit is cherry picked into a patch stack managed branch. Most commonly this occurs with the gps branch, gps request-review, and gps integrate commands.

**Comment by jameswalmsley** [comment]
This is a great explanation, many thanks.
I think a tag like:

```
<!-- https://git-ps.sh: 076e197b-235c-442e-a9ae-5c01672f18b7-->
```

Would be best. It's not overtly marketing in the commit log, but provides a stronger link for curious developers to read up on git-ps etc.

**Comment by drewdeponte** [comment]
I had a few thoughts around this. We could support something like the following.

```
https://git-ps.sh/patch/076e197b-235c-442e-a9ae-5c01672f18b7
```

Maybe we could even spin up something to redirect back. Maybe that would be confusing.

```
ps-id: 076e197b-235c-442e-a9ae-5c01672f18b7

Patch brought to you by https://git-ps.sh
```

**Comment by Alizter** [comment]
The reservation that my teams have which is not quite covered here is that `git log` is read sometimes and becomes bloated with ps ids. I am not the only one on the team using gps however we have been asked to remove psid manually. When using gps branch this does not become a problem for me personally.

**Comment by drewdeponte** [comment]
Hmm, one potential idea would be maybe adding support to the `integrate` command to strip the ps-id out prior to integration.

**Comment by drewdeponte** [comment]
But while it is in a PR it is there

**Comment by drewdeponte** [comment]
This has been integrated into mainline of the book repository. Therefore, I am closing this issue.
