### ISSUE TITLE
add config option for alternating background color in gps ls

### ISSUE THREAD

**Issue by Alizter** [uptech/git-ps-rs#283]
We should add two configuration options for the alternating background color when you do `gps ls`. 

1. The color value of the background. We could stick to ansi 256 or just allow a hex value 0xffffff a la web.
2. Enabling and disabling the colouring all together. Some terminals have transparent backgrounds so no background color looks best.

**Comment by Alizter** [comment]
Here is an example of how it can look today:

![image](https://github.com/uptech/git-ps-rs/assets/8614547/621a11a9-bb90-4ebb-a6d2-5ec007130ba9)

**Comment by drewdeponte** [comment]
My instinct is that we need to provide a `colors` section of the config that maybe has the following options.

- **enabled**: `true`/`false`
- **mode**: `16`, `256`, `24bit` (this of course depends on what color library supports
- **patch_series_color** - color for the patch series (depends on mode)
- **alternating_patch_series_color** - color for alternating patch series (depends on mode)
- **patch_index** - color for the patch index
- **patch_sha** - color for the patch sha
- **patch_summary** - color for the patch summary
- etc...

**Comment by Alizter** [comment]
I think that the configuration options described here are nice, but I wouldn't regard them as strictly necessary. I think just an enabled/disabled option should be enough for the next release.

**Comment by drewdeponte** [comment]
We talked about this in Slack and we netted that we should probably just start with 24bit color mode support and if someone isn't using a term that supports it then they can for the time being disable color all together. In the future we will potentially try and figure out supporting 256 color mode and 16 color mode.

We also discussed an initial structuring of the config related to colors such that we would have something like the following.

```
[colors]
warning_foreground_color =

[list]
patch_series_background_color =
patch_series_foreground_color =
patch_series_index_foreground_color =
patch_series_sha_foreground_color =
patch_series_summary_color =
alternate_patch_series_background_color =
alternate_patch_series_foreground_color =
alternate_patch_series_index_foreground_color =
alternate_patch_series_sha_foreground_color =
alternate_patch_series_summary_color =
...
```

**Comment by drewdeponte** [comment]
this has been integrated into `main` with shas d00aea5, 3482d86, and 0bb5349. Therefore, I am closing this issue.
