### ISSUE TITLE
the `integrate` command updates the PR before merging should it?

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#38]
@RyanHedges sent me the following via Slack message:

> It looks like git-ps pub updates the pull request branch before merging. As a result, the [bitbucket pipeline’s pull request](https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/#pull-requests) option kicks off. Then when the commit is cherry picked onto main, and deletes the branch, the pipeline fails because the branch no longer exists. I know it isn’t technically a git-ps problem, but wanted to let you know as other people may run into this. We’re looking to see if there is a pipeline configuration that can help avoid this. I do wonder though, does the `pub` need to update the existing branch before it deletes it?

@ctsstc replied to him with the following:

> Does pub currently cherry pick the index out and rebase it to master? I haven’t used it in a long while. It almost seems like it should have a branch in the background that stays consistent and it would just utilize that, but I could see where it could get out of sync and require rebasing if anything changes below it in the stack.

@frankylee then replied with the following:

> For bitbucket, @chillbrodev  and I added the `-k` flag, so each pub command looked like this: `git ps pub <patch> -k`

**Comment by chillbrodev** [comment]
I think it should update the PR, otherwise the PR has out of date information if one was to go back and review closed PRs.

**Comment by drewdeponte** [comment]
@Ryan, I think there are two separate points of discussion here that are somewhat intertwined

Lets start by addressing @Cody's question and reviewing how it currently works and why. Currently the way it works is by cherry-picking the patch to it's associated request-review branch, push that branch up to upstream either creating the remote branch if publishing without a review or updating the remote branch if publishing with previously requesting review. Then it pushes the request-review branch up to upstream's mainline (e.g. `git push origin ps/rr/whatever-patch:main`). This has the following benefits.

* it supports being able to `integrate` a patch that hasn't had a review requested (if you really want to by providing a `-f` command line switch) - I personally use this quite a bit on my personal side projects
* if you had any additional changes to the patch in your local patch stack, it updates the branch, and integrates effectively exactly the patch that is in your local patch stack (treating your patch stack as truth)

Now this does have some drawbacks.

* it triggers additional CI builds (maybe necessary or maybe not), and when combined with the cleanup step of nuking the branches causes CI builds to fail because the branches have been cleaned up, which in the case of needing the CI to run doesn't help and in the case of not needing CI to run just creates noise.
* if you had local changes to the patch that you hadn't requested review for yet, you could be integrating code which hasn't been reviewed.

An alternative approach we could take would be to treat the patch in the `ps/rr/whatever` branch as truth and integrate that into upstream rather than integrating the patch as it exists in your local patch stack. This would have the following benefits.

* we don't need to update the `ps/rr/whatever-branch`
* preventing us from triggering additional CI builds
* preventing the cleanup from causing CI failures.

The drawbacks.

* any changes between the local patch in the patch stack and what is in the request-review branch wouldn't be integrated and when you do a `git ps pull` you would be forced to resolve any of the conflicts
* introduces complexities (what do we do if that request-review branch has other commits in it) - there is no guarantee it is just a patch anymore

Looking at the above it seems like these drawbacks could potentially be addressed. The first one isn't so much a drawback it is more shifting resolution of the difference which could be a good thing maybe, I am not 100% sure off hand. In terms of the second drawback maybe we have it perform the following checks.

* verify that the request-review branch only has one commit in it and that the commit is a patch, if it doesn't then error out telling the user why. Then the user would have to get it into this state prior to being able to integrate by pulling the additional commits into their local patch stack (no current patch stack operation for this yet, but have been thinking about it), squashing them into the logical patch, and then syncing that patch.
* once we know we have a single patch we can do a check to verify that the patch contents are the same between the patch specified in the local patch stack and the patch existing in the request-review branch.

I believe the above would address all of the drawbacks we have identified and enable the integrate cleaning up the branches for you without causing issues. This all seems great within the scope of a single patch.

I guess in theory it should be fine with a patch series if we decide to add that functionality back. It would just have to go through the series and verify each of the patches in the request-review branch and make sure nothing more or less is there.

I think this might be a better approach? What do you all think?

**Comment by RyanHedges** [comment]
I think this does makes sense. Stepping back a little, there may be some other things to consider that can help drive us towards a good solution. I haven't thought deeply on this, so please excuse any incorrect assumptions I make. 😄 

You shared that your local stack is the source of truth, and the `ps/rr/whatever` branch could be the new source of truth. Is there a way where the commit shas could be the source of truth? If my commit sha hasn't changed, then when I pub, we don't need to trigger any changes to upstream. If my sha has changed we say we can't integrate, because things have changed. When I do a interactive rebase and squash a commit, a new sha is created. If I do an interactive rebase and reword the commit, the sha changes. It seems like git ps currently doesn't really care if there is a change made or not and updates things based on the assumption that things may have changed. If I `rr`, it updates, if I pub it updates. 

If git-ps does the check for me based on sha, it could do smart things based on the situation, it could prompt me "hey what do you want to do?", it could be skipped checks by `-f`.

In my workflow, I use `rr` to update remote with what I've done locally. I assume that when I pub a patch that doesn't have `rr+` next to it, it shouldn't do anything other than merge and clean up branches. Obviously, things are more complicated than that under the hood, but hopefully that helps give some context to inform a solution.

Hopefully my stream of thoughts are helpful.

**Comment by chillbrodev** [comment]
Im not sure if treating the PR as the source of truth is a good thing. Or perhaps could you elaborate further on what you mean by that?  
---
This `preventing us from triggering additional CI builds` is a concern to me. When you `git ps rr #` and re-update the PR, it should re-trigger the CI.

**Comment by drewdeponte** [comment]
@chillbrodev we aren't talking about the `rr` command. We are talking about the `integrate` command which used to be called `pub` pre git-ps-rs.

So we are saying that `integrate` wouldn't trigger CI builds.

**Comment by chillbrodev** [comment]
@drewdeponte Ah my mistake, I read it when thinking about `rr`.

**Comment by drewdeponte** [comment]
Yeah, I think this makes sense to change how this works such that `integrate` basically does the verification steps to make sure the patch and the remote branch are in-sync, does the actual integration of the remote branch into upstream, and then cleans up the branches (both local and remote) for the user.

This makes it so that it won't trigger CI builds when they aren't needed and so that `integrate` won't cause CI builds that are guaranteed to fail with most CI systems.

It just means if things aren't synced it will error out and tell you to sync your changes first so that they can be reviewed.

**Comment by drewdeponte** [comment]
This has been integrated into mainline.
