### ISSUE TITLE
Add ability to use 'Y' and 'N' in place of 'Yes' & 'No' when integrating a patch

### ISSUE THREAD

**Issue by chillbrodev** [uptech/git-ps-rs#69]
When integrating a patch it prompts for Yes/No. It would be great to use 'Y' or 'N' instead of typing out the full word
<img width="708" alt="image" src="https://user-images.githubusercontent.com/2694785/166339938-be2a280f-be62-4f24-9765-2d5b6f16770e.png">

**Comment by drewdeponte** [comment]
Does this make it too easy @RyanHedges?

**Comment by RyanHedges** [comment]
/shrug

I think I would prefer to have `y` or `n` work. This step is supposed to help be the check. If you're in autopilot mode, then... that's not git-ps's problem.

I do agree typing `yes` does slow me down, but I'm not reflecting on if I should integrate or not. I've mentally already made the choice to continue with the integration.

At least that's my rational for allowing `y` and `n`. :)

**Comment by drewdeponte** [comment]
At the moment this basically checks for "yes" or anything not that is the no. So should be as simple as modifying it to be an or conditional to be "yes" || "y".

**Comment by drewdeponte** [comment]
I am closing this issue as it has been resolved and integrated into mainline.

**Comment by chillbrodev** [comment]
Oh cool
