### ISSUE TITLE
Modify README.md around example hook

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#70]
@chillbrodev provided some great feedback that we should rework this section to be clear that we are providing a specific example  of the simple basic GitHub one but that you can use this hook to do whatever you want.

That way the newbs are able to quickly get up and running without running into issues with hooks out of the gate like not having the `gh` command installed or not being authentication via it.

**Comment by chillbrodev** [comment]
I'll pick this up today and add the info we discussed

**Comment by drewdeponte** [comment]
Closing this issue as it has been integrated into mainline.
