### ISSUE TITLE
gps int seems to sometimes collapse away integrated patches and other times not

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-ps-rs#78]
I am not sure why this is off hand. I don't believe we implemented anything to explicitly do a fetch or anything to collapse away the integrated patches.

It is also strange that it is inconsistent. It doesn't seem to be related to an actual problem with the Git tree as far as I can tell in all of my testing.

It is just annoying because in scenarios where you want to integrate the bottom 3 patches that have all been approved. You need to basically do the following:

1. `gps int patchA`
2. `gps ls` - to see if the integrated patch A was collapsed away or not so that you can figure out the next patches index now
3. `gps int patchB's index`
4. `gps ls` - to see if the integrated patch B was collapsed away or not so that you can figure out the next patches index now
5. `gps int patchC's index`
6. etc.

With the old incarnation of git-ps it was consistent and you could simply do the following:

1. `gps int 0`
2. `gps int 1`
3. `gps int 2`
4. `gps pull` - to collapse away the integrated patches

**Comment by drewdeponte** [comment]
I did some digging into this and it seems to be happening in some cases (not exactly sure) where it seems instead of creating a copy of the commit with a different SHA and pointing the `ps/rr/whatever` branch reference at that. Some how the `ps/rr/whatever` branch and `main` end up pointing at the same SHA. Therefore, when the patch in the `ps/rr/whatever` branch is integrated into `origin/main` it naturally collapses the patch out of the stack because it is the same patch.

What I expected to happen and to be the case all of the time is that it should create a copy of the commit with a different SHA in the `ps/rr/whatever` branch. When this does occur this process works as expected and the patch isn't collapsed out of the stack until you `gps pull`.

So the trick now is figuring out exactly what is causing the `request-review-branch` process to in some cases create a copy of the commit in the `ps/rr/whatever` branch and figure out why in other cases (and what cases) it ends up with them both being the same commit and resulting in this problem.

**Comment by drewdeponte** [comment]
I added some logging locally to the `create_gpg_signed_commit()` function as I suspected after reading the code that the `new_commit_oid` was some how coming back the same when adding a patch stack id to a commit and when it cherry picks the commit to the `ps/rr/whatever` branch.

Sure enough that seems to be the case per the following output.

```
DREW: dest_ref_name = refs/heads/ps/tmp/add_id_rework
DREW: destination_oid = c84f4f16b9b5c587715bdf5786f9ef12986a32c5
DREW: new_commit_oid = 3db9c7be05c5d4f3e0760cef01f2563b4d006c74
DREW: dest_ref_name = refs/heads/ps/rr/add_your_mom_to_chapter_1
DREW: destination_oid = c84f4f16b9b5c587715bdf5786f9ef12986a32c5
DREW: new_commit_oid = 3db9c7be05c5d4f3e0760cef01f2563b4d006c74
```

So right now I think it only happens when it first adds a patch stack id to a commit and then follows up with the cherry-pick to the branch. I am not 100% sure that is the case. But that is what it is seeming like.

**Comment by drewdeponte** [comment]
You can produce this scenario by starting with an empty stack.

1. make some changes and create a commit on the stack
2. `gps request-review-branch 0` to run the process
3. inspect the Git tree to see that the `ps/rr/whatever` branch and `main` point to the same commit when they shouldn't

You can reset state in the repo after this by doing the following:

1. `git branch -D ps/rr/whatever` to delete the local branch
2. `git reset --hard origin/main` reset your stack to empty
3. `rm .git/GIT-PATCH-STACK-PATCH-STATES-V3.json` - remove git patch stacks state to reset it

Then you should be good to do the above all over again.

**Comment by drewdeponte** [comment]
Did some further testing and discovered that it is producing the same SHA because all of the content is the same. Even the committer signature and it's associated timestamp which we would expect to change.

Turns out that the committer timestamp is only down to the granularity of seconds since epoch. Because we are doing the add patch stack id to commit process and then cherry picking the commit into the `ps/rr/whatever` branch process generally within the same second it is computing the same SHA which in turn is resulting in the references being pointed to the same SHA.

I discussed this with @philipcolejohnson and we explored offsetting the committer timestamp a number of seconds into the past or into the future. After some debate and exploration we have decided that the thing that makes the most sense is to offset the committer time forward 1 second when doing the cherry pick of the commit into the `ps/rr/whatever` branch.

We think this makes the most sense because it is a scenario that is natural and can happen anyways if you are on the threshold of the second turn over. For example the add patch stack id can happen, then the second can turn over, and then the cherry pick to the request review branch can happen. So we will effectively be pushing it over only when cherry picking into the request review branch.

**Comment by drewdeponte** [comment]
This issue has been integrated into mainline and released as part of v5.3.0. Therefore I am closing this issue.

**Comment by RyanHedges** [comment]
I did a quick skim of this issue so sorry if I missed something. I believe I've seen this happen with my `sync`ed patches when integrating them. Sometimes I have to do a `gps pull` after the integrate and sometimes I don't. Is that the same issue described here? Will this fix address it or is it just for those that use `rr`?

**Comment by drewdeponte** [comment]
@RyanHedges this is that issue and it does fix/address that issue.

The way it fixes/addresses the issue is by making the behavior consistent for the following flow.

1. `gps int`
2. `gps ls` - now you will consistently see the patch you just integrated with the `int` status next to it
3. `gps pull` - this will collapse away the integrated patches
